services:
  my-ci:
    image: ghcr.io/geoffsee/my-ci:latest
    pull_policy: build
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "7878:7878"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./my-ci:/work/my-ci
      - my-ci-history:/work/.my-ci

volumes:
  my-ci-history:
